# Config file for automatic testing at travis-ci.org

language: python
python: "2.7"

env:
  - TOX_ENV=py27-django14
  - TOX_ENV=py27-django15
  - TOX_ENV=py27-django16
  - TOX_ENV=py33-django15
  - TOX_ENV=py33-django16

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install tox
  - pip install coveralls

# command to run tests, e.g. python setup.py test
script: tox -e $TOX_ENV

after_success: coveralls
