# Config file for automatic testing at travis-ci.org

language: python
python: "3.4"

env:
  - TOX_ENV=py27-django14
  - TOX_ENV=py27-django15
  - TOX_ENV=py27-django16
  - TOX_ENV=py27-django17
  - TOX_ENV=py27-django18
  - TOX_ENV=py34-django15
  - TOX_ENV=py34-django16
  - TOX_ENV=py34-django17
  - TOX_ENV=py34-django18

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install --upgrade pip
  - pip install tox
  - pip install coveralls

services:
  - redis-server

# command to run tests, e.g. python setup.py test
script: tox -e $TOX_ENV

after_success: coveralls
